name:                muprl
version:             0.1.0.0
github:              "totbwf/muprl"
license:             BSD3
author:              "Reed Mullanix"
maintainer:          "reedmullanix@egmail.com"
copyright:           "2018 Reed Mullanix"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/totbwf/muprl#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec >= 6 && < 7
- lens >= 4 && < 5
- mtl >= 2 && < 3
- text >= 1 && < 2
- prettyprinter >= 1 && < 2
- prettyprinter-ansi-terminal >= 1 && < 2
- unbound-generics >= 0.4 && < 0.5
- haskeline >= 0.7 && < 0.8
- ansi-terminal >= 0.8 && < 0.9
- containers >= 0.5 && < 0.6
- haskell-lsp >= 0.2 && < 0.3
- refinery >= 0.1 && < 0.2

default-extensions:
- TupleSections
- LambdaCase
- MultiWayIf
- FlexibleContexts
- FlexibleInstances
- MultiParamTypeClasses
- DeriveFunctor
- DeriveTraversable
- DeriveFoldable
- DeriveDataTypeable 
- DeriveGeneric 
- ScopedTypeVariables
- ViewPatterns
- GeneralizedNewtypeDeriving

library:
  source-dirs:         src

executables:
  muprl:
    main:                main/Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

    dependencies:
    - muprl
    - optparse-applicative >= 0.14 && < 0.15
    

tests:
  muprl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - muprl
    - hspec
